#!/usr/bin/env bash


if [[ "$(uname)" == "Darwin" ]]; then
    brew install ghostty
    exit 0
fi

# taken from https://github.com/ThePrimeagen/dev/blob/master/runs/ghostty
sudo apt update
sudo apt install llvm lld llvm-dev liblld-dev clang libclang-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev git

wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz -O /tmp/zig.tar.xz
tar -xvf /tmp/zig.tar.xz -C $HOME/.local
export PATH="$HOME/.local/zig-linux-x86_64-0.13.0:$PATH"

mkdir -p $HOME/workspace/github
export GHOSTTY_DIR=$HOME/workspace/github/ghostty
export GHOSTTY_TAG=v1.1.3

if [ ! -d "$GHOSTTY_DIR" ]; then
git clone git@github.com:ghostty-org/ghostty.git $GHOSTTY_DIR
else
    cd $GHOSTTY_DIR
    git checkout main
    git pull
fi


cd $GHOSTTY_DIR
git checkout $GHOSTTY_TAG
zig build -p $HOME/.local -Doptimize=ReleaseFast
