#!/usr/bin/env bash


if [[ "$(uname)" == "Darwin" ]]; then
    brew install ghostty
    exit 0
fi

sudo apt update
sudo apt install \
  libgtk-4-dev \
  libgtk4-layer-shell-dev \
  libadwaita-1-dev \
  gettext \
  libxml2-utils \
  blueprint-compiler 

wget https://ziglang.org/download/0.14.1/zig-linux-x86_64-0.14.1.tar.xz -O /tmp/zig.tar.xz
tar -xvf /tmp/zig.tar.xz -C $HOME/.local
export PATH="$HOME/.local/zig-linux-x86_64-0.14.1:$PATH"

mkdir -p $HOME/workspace/github
export GHOSTTY_DIR=$HOME/workspace/github/ghostty
export GHOSTTY_TAG=v1.2.0

if [ ! -d "$GHOSTTY_DIR" ]; then
git clone git@github.com:ghostty-org/ghostty.git $GHOSTTY_DIR
else
    cd $GHOSTTY_DIR
    git checkout main
    git pull
fi


cd $GHOSTTY_DIR
git checkout $GHOSTTY_TAG

zig build -p $HOME/.local -Doptimize=ReleaseFast
