#!/usr/bin/env bash

if [[ "$(uname)" != "Darwin" ]]; then
    echo "Not a Mac...skipping"
    exit 0
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew --version
