#!/usr/bin/env bash

pushd /tmp
  rm -rf nvim
  git clone --depth 1 --branch v0.10.4 https://github.com/neovim/neovim.git
  pushd neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$HOME/nvim
    make install
  popd
popd

