#!/usr/bin/env bash
set -xe

ZIG_VERSION=0.14.0
if [[ "$(uname)" == "Darwin" ]]; then
    FILENAME=zig-macos-aarch64-$ZIG_VERSION
else
    FILENAME=zig-linux-x86_64-$ZIG_VERSION
fi

rm -f /tmp/zig.tar.xz
curl https://ziglang.org/download/$ZIG_VERSION/$FILENAME.tar.xz -o /tmp/zig.tar.xz
curl https://ziglang.org/download/$ZIG_VERSION/$FILENAME.tar.xz.minisig -o /tmp/zig.tar.xz.minisig

minisign -Vm /tmp/zig.tar.xz -P RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U

rm -rf $HOME/.local/$FILENAME || true
rm -rf $HOME/.local/zig
tar -xvf /tmp/zig.tar.xz -C $HOME/.local
mv $HOME/.local/$FILENAME $HOME/.local/zig
