#!/usr/bin/env bash
set -xe

ZIG_VERSION=0.15.2
if [[ "$(uname)" == "Darwin" ]]; then
    FILENAME=zig-x86_64-macos-$ZIG_VERSION
else
    FILENAME=zig-x86_64-linux-$ZIG_VERSION
fi

rm -f /tmp/zig.tar.xz
curl https://ziglang.org/download/$ZIG_VERSION/$FILENAME.tar.xz -o /tmp/zig.tar.xz
curl https://ziglang.org/download/$ZIG_VERSION/$FILENAME.tar.xz.minisig -o /tmp/zig.tar.xz.minisig

minisign -Vm /tmp/zig.tar.xz -P RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U

rm -rf $HOME/.local/$FILENAME || true
rm -rf $HOME/.local/zig
tar -xvf /tmp/zig.tar.xz -C $HOME/.local
mv $HOME/.local/$FILENAME $HOME/.local/zig
