#!/usr/bin/env bash

if [[ "$(pwd)" == "$HOME" ]]; then
    clear
    return
fi


tmux new-window -dn scratch
[ -f pyproject.toml ] || [ -f setup.py ] && wo . && tmux send-keys -t "scratch" 'wo .' Enter
nvim .
clear
