#!/usr/bin/env zsh

tmux_running=$(pgrep tmux)
fd="/usr/bin/fdfind"

if [[ "$(uname)" == "Darwin" ]]; then
    fd="/opt/homebrew/bin/fd"
fi

fzf_args=()
if [[ "$TERM_PROGRAM" == "tmux" ]]; then
    fzf="fzf-tmux"
    fzf_args=("-p")
else
    fzf="fzf"
fi

if [[ $# -eq 1 ]]; then
    project_files=$1
else
    project_files=("$HOME/dotfiles")
    
    selected=$(for f in $(fd -HI .git$ --min-depth=1 --max-depth=3 --prune ~ ~/workspace ~/workspace/github); do
        echo $f
    done | uniq | sed -e 's/\.git\/$//' | sed -e 's/\/$//' | $fzf "$fzf_args[@]")
    
fi

if [[ -z $selected ]]; then
    exit 0
fi

echo "selected: $selected"

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    cd $selected
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    cd $selected
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi
